### ISSUE TITLE
Unable to install detectron2==0.6+cu111

### ISSUE THREAD

**Issue by MehreenNaeem** [snumprlab/capeam#2]
detectron2 requires Python ≥ 3.7 but capeam is build on Python3.6

**Comment by charlottejruby** [comment]
Detectron2 officially states that Python 3.7 or higher is required. However, it seems to work on Python 3.6 as well. Although the official documentation specifies Python 3.7 and above, I have successfully run Detectron2 on Python 3.6. This might be due to backward compatibility or specific configurations. 

I installed detectron2 in a Python 3.6 environment using the following command:
`python -m pip install detectron2 -f \
  https://dl.fbaipublicfiles.com/detectron2/wheels/cu111/torch1.8/index.html
`
